set(INCLUDES
    include/dna/BinaryStreamReader.h
    include/dna/BinaryStreamWriter.h
    include/dna/DataLayer.h
    include/dna/Defs.h
    include/dna/JSONStreamReader.h
    include/dna/JSONStreamWriter.h
    include/dna/Reader.h
    include/dna/StreamReader.h
    include/dna/StreamWriter.h
    include/dna/Writer.h
    include/dna/layers/BehaviorReader.h
    include/dna/layers/BehaviorWriter.h
    include/dna/layers/DefinitionReader.h
    include/dna/layers/DefinitionWriter.h
    include/dna/layers/Descriptor.h
    include/dna/layers/DescriptorReader.h
    include/dna/layers/DescriptorWriter.h
    include/dna/layers/Geometry.h
    include/dna/layers/GeometryReader.h
    include/dna/layers/GeometryWriter.h
    include/dna/types/Aliases.h
    include/dna/types/ArrayView.h
    include/dna/types/StringView.h
    include/dna/types/Vector3.h
    include/dna/version/Version.h
    include/dnacalib/Command.h
    include/dnacalib/DNACalib.h
    include/dnacalib/Defs.h
    include/dnacalib/commands/CalculateMeshLowerLODsCommand.h
    include/dnacalib/commands/ClearBlendShapesCommand.h
    include/dnacalib/commands/CommandSequence.h
    include/dnacalib/commands/ConditionalCommand.h
    include/dnacalib/commands/PruneBlendShapeTargetsCommand.h
    include/dnacalib/commands/RemoveAnimatedMapCommand.h
    include/dnacalib/commands/RemoveBlendShapeCommand.h
    include/dnacalib/commands/RemoveJointAnimationCommand.h
    include/dnacalib/commands/RemoveJointCommand.h
    include/dnacalib/commands/RemoveMeshCommand.h
    include/dnacalib/commands/RenameAnimatedMapCommand.h
    include/dnacalib/commands/RenameBlendShapeCommand.h
    include/dnacalib/commands/RenameJointCommand.h
    include/dnacalib/commands/RenameMeshCommand.h
    include/dnacalib/commands/RotateCommand.h
    include/dnacalib/commands/ScaleCommand.h
    include/dnacalib/commands/SetBlendShapeTargetDeltasCommand.h
    include/dnacalib/commands/SetLODsCommand.h
    include/dnacalib/commands/SetNeutralJointRotationsCommand.h
    include/dnacalib/commands/SetNeutralJointTranslationsCommand.h
    include/dnacalib/commands/SetSkinWeightsCommand.h
    include/dnacalib/commands/SetVertexPositionsCommand.h
    include/dnacalib/commands/TranslateCommand.h
    include/dnacalib/commands/VectorOperations.h
    include/dnacalib/dna/DNACalibDNAReader.h
    include/dnacalib/types/Aliases.h
    include/dnacalib/version/Version.h
    include/dnacalib/version/VersionInfo.h
    include/pma/Defs.h
    include/pma/MemoryResource.h
    include/pma/PolyAllocator.h
    include/pma/ScopedPtr.h
    include/pma/TypeDefs.h
    include/pma/resources/AlignedMemoryResource.h
    include/pma/resources/ArenaMemoryResource.h
    include/pma/resources/DefaultMemoryResource.h
    include/pma/utils/ManagedInstance.h
    include/pma/version/Version.h
    include/status/Defs.h
    include/status/Provider.h
    include/status/Status.h
    include/status/StatusCode.h
    include/status/version/Version.h
    include/trio/Concepts.h
    include/trio/Defs.h
    include/trio/Stream.h
    include/trio/streams/FileStream.h
    include/trio/streams/MemoryMappedFileStream.h
    include/trio/streams/MemoryStream.h
    include/trio/types/Aliases.h
    include/trio/types/Parameters.h
    include/trio/utils/StreamScope.h
    include/trio/version/Version.h)
set(SOURCES
    src/dna/BaseImpl.h
    src/dna/DNA.h
    src/dna/DataLayerBitmask.h
    src/dna/DenormalizedData.h
    src/dna/LODConstraint.cpp
    src/dna/LODConstraint.h
    src/dna/LODMapping.cpp
    src/dna/LODMapping.h
    src/dna/Reader.cpp
    src/dna/ReaderImpl.h
    src/dna/SurjectiveMapping.h
    src/dna/TypeDefs.h
    src/dna/Writer.cpp
    src/dna/WriterImpl.h
    src/dna/filters/AnimatedMapFilter.cpp
    src/dna/filters/AnimatedMapFilter.h
    src/dna/filters/BlendShapeFilter.cpp
    src/dna/filters/BlendShapeFilter.h
    src/dna/filters/JointFilter.cpp
    src/dna/filters/JointFilter.h
    src/dna/filters/MeshFilter.cpp
    src/dna/filters/MeshFilter.h
    src/dna/filters/Remap.h
    src/dna/stream/BinaryStreamReaderImpl.cpp
    src/dna/stream/BinaryStreamReaderImpl.h
    src/dna/stream/BinaryStreamWriterImpl.cpp
    src/dna/stream/BinaryStreamWriterImpl.h
    src/dna/stream/FilteredInputArchive.cpp
    src/dna/stream/FilteredInputArchive.h
    src/dna/stream/JSONStreamReaderImpl.cpp
    src/dna/stream/JSONStreamReaderImpl.h
    src/dna/stream/JSONStreamWriterImpl.cpp
    src/dna/stream/JSONStreamWriterImpl.h
    src/dna/stream/StreamReader.cpp
    src/dna/stream/StreamWriter.cpp
    src/dna/types/Limits.h
    src/dna/utils/Extd.h
    src/dna/utils/ScopedEnumEx.h
    src/dnacalib/Command.cpp
    src/dnacalib/CommandImplBase.h
    src/dnacalib/TypeDefs.h
    src/dnacalib/commands/CalculateMeshLowerLODsCommand.cpp
    src/dnacalib/commands/ClearBlendShapesCommand.cpp
    src/dnacalib/commands/CommandSequence.cpp
    src/dnacalib/commands/PruneBlendShapeTargetsCommand.cpp
    src/dnacalib/commands/RemoveAnimatedMapCommand.cpp
    src/dnacalib/commands/RemoveBlendShapeCommand.cpp
    src/dnacalib/commands/RemoveJointAnimationCommand.cpp
    src/dnacalib/commands/RemoveJointCommand.cpp
    src/dnacalib/commands/RemoveMeshCommand.cpp
    src/dnacalib/commands/RenameAnimatedMapCommand.cpp
    src/dnacalib/commands/RenameBlendShapeCommand.cpp
    src/dnacalib/commands/RenameJointCommand.cpp
    src/dnacalib/commands/RenameMeshCommand.cpp
    src/dnacalib/commands/RenameResourceCommand.h
    src/dnacalib/commands/RotateCommand.cpp
    src/dnacalib/commands/ScaleCommand.cpp
    src/dnacalib/commands/SetBlendShapeTargetDeltasCommand.cpp
    src/dnacalib/commands/SetLODsCommand.cpp
    src/dnacalib/commands/SetNeutralJointRotationsCommand.cpp
    src/dnacalib/commands/SetNeutralJointTranslationsCommand.cpp
    src/dnacalib/commands/SetSkinWeightsCommand.cpp
    src/dnacalib/commands/SetVertexPositionsCommand.cpp
    src/dnacalib/commands/SupportFactories.h
    src/dnacalib/commands/TranslateCommand.cpp
    src/dnacalib/dna/BaseImpl.h
    src/dnacalib/dna/DNA.h
    src/dnacalib/dna/DNACalibDNAReaderImpl.cpp
    src/dnacalib/dna/DNACalibDNAReaderImpl.h
    src/dnacalib/dna/DenormalizedData.h
    src/dnacalib/dna/LODConstraint.cpp
    src/dnacalib/dna/LODConstraint.h
    src/dnacalib/dna/LODMapping.cpp
    src/dnacalib/dna/LODMapping.h
    src/dnacalib/dna/ReaderImpl.h
    src/dnacalib/dna/SurjectiveMapping.h
    src/dnacalib/dna/WriterImpl.h
    src/dnacalib/dna/filters/AnimatedMapFilter.cpp
    src/dnacalib/dna/filters/AnimatedMapFilter.h
    src/dnacalib/dna/filters/BlendShapeFilter.cpp
    src/dnacalib/dna/filters/BlendShapeFilter.h
    src/dnacalib/dna/filters/JointFilter.cpp
    src/dnacalib/dna/filters/JointFilter.h
    src/dnacalib/dna/filters/MeshFilter.cpp
    src/dnacalib/dna/filters/MeshFilter.h
    src/dnacalib/dna/filters/Remap.h
    src/dnacalib/types/BoundingBox.h
    src/dnacalib/types/Triangle.cpp
    src/dnacalib/types/Triangle.h
    src/dnacalib/types/UVBarycentricMapping.cpp
    src/dnacalib/types/UVBarycentricMapping.h
    src/dnacalib/utils/Algorithm.h
    src/dnacalib/utils/Extd.h
    src/dnacalib/utils/FormatString.h
    src/dnacalib/utils/ScopedEnumEx.h
    src/dnacalib/version/VersionInfo.cpp
    src/pma/MemoryResource.cpp
    src/pma/resources/AlignedMemoryResource.cpp
    src/pma/resources/ArenaMemoryResource.cpp
    src/pma/resources/DefaultMemoryResource.cpp
    src/status/PredefinedCodes.h
    src/status/Provider.cpp
    src/status/Registry.cpp
    src/status/Registry.h
    src/status/Status.cpp
    src/status/Storage.cpp
    src/status/Storage.h
    src/tdm/Computations.h
    src/tdm/Mat.h
    src/tdm/TDM.h
    src/tdm/Transforms.h
    src/tdm/Types.h
    src/tdm/Vec.h
    src/tdm/version/Version.h
    src/terse/Archive.h
    src/terse/archives/Common.h
    src/terse/archives/Traits.h
    src/terse/archives/binary/InputArchive.h
    src/terse/archives/binary/OutputArchive.h
    src/terse/archives/json/InputArchive.h
    src/terse/archives/json/OutputArchive.h
    src/terse/types/Anchor.h
    src/terse/types/ArchiveOffset.h
    src/terse/types/ArchiveSize.h
    src/terse/types/Blob.h
    src/terse/types/CharInputStreamBuf.h
    src/terse/types/CharOutputStreamBuf.h
    src/terse/types/DynArray.h
    src/terse/types/Transparent.h
    src/terse/utils/Base64.h
    src/terse/utils/ByteSwap.h
    src/terse/utils/Endianness.h
    src/terse/utils/VirtualSerializerProxy.h
    src/terse/version/Version.h
    src/trio/Concepts.cpp
    src/trio/Stream.cpp
    src/trio/streams/FileStreamImpl.cpp
    src/trio/streams/FileStreamImpl.h
    src/trio/streams/MemoryMappedFileStream.cpp
    src/trio/streams/MemoryMappedFileStreamFallback.cpp
    src/trio/streams/MemoryMappedFileStreamFallback.h
    src/trio/streams/MemoryMappedFileStreamUnix.cpp
    src/trio/streams/MemoryMappedFileStreamUnix.h
    src/trio/streams/MemoryMappedFileStreamWindows.cpp
    src/trio/streams/MemoryMappedFileStreamWindows.h
    src/trio/streams/MemoryStreamImpl.cpp
    src/trio/streams/MemoryStreamImpl.h
    src/trio/streams/StreamStatus.cpp
    src/trio/streams/StreamStatus.h
    src/trio/utils/NativeString.h
    src/trio/utils/PlatformWindows.h
    src/trio/utils/ScopedEnumEx.h)
set(TESTS
    )
